[ntainer#0-0-C-1] essageListenerContainer$ListenerConsumer : Stopping container due to an Error
java.lang.NoSuchMethodError: org.apache.kafka.clients.consumer.Consumer.poll(Ljava/time/Duration;)Lorg/apache/kafka/clients/consumer/ConsumerRecords;
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.pollAndInvoke(KafkaMessageListenerContainer.java:741) ~[spring-kafka-2.2.6.RELEASE.jar:2.2.6.RELEASE]

bug小半天了 一直没解决